Repository wecode-bootcamp-korea/33-1st-crowsSeven-frontend, pull requests merged in 2022-05, with the labels that each got.

#2 [33기 김완영]MODIFY:리뷰 반영, ADD:searchBox 애니메이션 추가
  public/data/backimageData.json
  public/data/slideData.json
  src/Router.js
  src/components/Nav.js
  src/components/Nav/Logo.js
  src/components/Nav/Logo.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/RightBoxNav.js
  src/components/Nav/RightBoxNav.scss
  src/components/Nav/SearchBox.js
  src/components/Nav/SearchBox.scss
  src/index.js
Labels: 수정 요청

#9 [33기 염종은]ADD:Singup 레이아웃 구현
  src/Router.js
  src/pages/Signup/Agreement.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/agreeData.js
Labels: 완료

#11 [33기 유하은] ADD: 장바구니 구현
  public/data/cartList.JSON
  src/Router.js
  src/components/Nav/Nav.scss
  src/components/Nav/SearchBox.scss
  src/index.js
  src/pages/cart/Cart.js
  src/pages/cart/Cart.scss
  src/pages/cart/CartEmpty.js
  src/pages/cart/CartItem.js
  src/pages/cart/CartItem.scss
  src/pages/cart/CartNotEmpty.js
Labels: 멘토 리뷰 요청

#15 [33기 김완영 ] ADD: 캐러셀 기능 구현
  public/data/carouselData.json
  src/pages/main/Carousel.js
  src/pages/main/Carousel.scss
  src/pages/main/CarouselCard.js
  src/pages/main/CarouselCard.scss
Labels: 멘토 리뷰 요청

#5 [33기 신윤지] 후기 페이지 게시글 충돌 수정
  public/data/relatedProductData.json
  src/Router.js
  src/components/Nav/Nav.scss
  src/components/review/TextItem.js
  src/review/Post.js
  src/review/Post.scss
Labels: 멘토 리뷰 요청

#14 [33기 박슬기] 상품 상세페이지 1차 완료
  public/data/ITEM_LIST.json
  src/Router.js
  src/components/Nav/Nav.scss
  src/pages/productDetail/ProductDetail.js
  src/pages/productDetail/ProductDetail.scss
  src/pages/productDetail/QnADrawer.js
  src/pages/productDetail/ReviewDrawer.js
  src/pages/store/Items.js
  src/pages/store/PageList.js
  src/pages/store/Store.js
  src/pages/store/Store.scss
Labels: 멘토 리뷰 요청

#12 [33기 김완영] MODIFY:리뷰반영 및 라우터 연결, scss 다듬기
  public/data/reviewData.json
  public/index.html
  src/Router.js
  src/components/Nav/Logo.js
  src/components/Nav/Logo.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/RightBoxNav.js
  src/components/Nav/RightBoxNav.scss
  src/components/Nav/SearchBox.scss
  src/components/reviews/TextItem.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/cart/Cart.js
  src/pages/cart/Cart.scss
  src/pages/main/Carousel.js
  src/pages/main/Carousel.scss
  src/pages/main/CarouselCard.scss
  src/pages/main/Footer.js
  src/pages/main/Footer.scss
  src/pages/main/Main.js
  src/pages/main/Main.scss
  src/pages/main/MainButton.js
  src/pages/main/MainButton.scss
  src/pages/main/SectionImg.js
  src/pages/main/SectionImg.scss
  src/pages/productDetail/ProductDetail.js
  src/pages/productDetail/ProductDetail.scss
  src/pages/productDetail/ReviewDrawer.js
  src/pages/review/Post.js
  src/pages/review/Post.scss
Labels: 멘토 리뷰 요청

#18 [33기 박슬기] 상품 목록페이지 1차 완료
  src/pages/store/Items.js
  src/pages/store/Store.js
  src/pages/store/Store.scss
Labels: 멘토 리뷰 요청

#10 [33기 염종은]ADD:ordercheck 페이지 layout
  public/data/cartList.JSON
  src/Router.js
  src/pages/DeleteOrder/DeleteOrder.js
  src/pages/OrderCheck/OrderCheck.js
  src/pages/OrderCheck/OrderCheck.scss
  src/pages/OrderCheck/OrderEmpty.js
  src/pages/OrderCheck/OrderItem.js
  src/pages/OrderCheck/OrderNotEmpty.js
  src/pages/cart/Cart.scss
Labels: 멘토 리뷰 요청

#13 [33기 염종은] Signup 페이지 기능 구현
  src/pages/Signup/Agreement.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/agreeData.js
Labels: 멘토 리뷰 요청

#16 [33기 유하은] ADD: 주문서 구현
  public/data/cartListData.json
  src/Router.js
  src/pages/Order/CartTable.js
  src/pages/Order/CartTable.scss
  src/pages/Order/OrderInfo.js
  src/pages/Order/OrderInfo.scss
  src/pages/Order/OrderPage.js
  src/pages/Order/OrderPage.scss
Labels: 멘토 리뷰 요청

#22 [33기 염종은] ADD:MyPage Layout
  package-lock.json
  package.json
  public/data/mypageData.json
  src/Router.js
  src/pages/mypage/LinkPage.js
  src/pages/mypage/MyPage.js
  src/pages/mypage/MyPage.scss
  src/pages/mypage/OrderStatus.js
  src/pages/mypage/linkData.js
  src/pages/mypage/orderStatusData.js
Labels: 멘토 리뷰 요청

#25 [33기 김완영] throttle 다른 branch에서 작업하기위해 제거, scrollY 값 수정
  src/components/Nav/Nav.js
  src/pages/main/Main.js
Labels: 멘토 리뷰 요청

#17 [33기 신윤지]ADD: review_page UI 구현 & 목데이터로 map 구성 & state로 back 보낼 데이터 취합
  public/data/relatedProductData.json
  src/Router.js
  src/components/reviews/ReviewPost.js
  src/components/reviews/TextItem.js
  src/pages/review/Post.js
  src/pages/review/Post.scss
  src/pages/review/PostForm.js
  src/pages/review/PostForm.scss
  src/pages/review/ReviewPage.js
  src/pages/review/ReviewPage.scss
Labels: 멘토 리뷰 요청

#19 [33기 염종은] Modify: login 페이지 백앤드 통해 로그인 구현 및 추가 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#20 [33기 유하은] ADD: 장바구니 기능구현
  public/data/cartList.JSON
  public/data/cartListData.json
  src/Router.js
  src/pages/cart/Cart.js
  src/pages/cart/Cart.scss
  src/pages/cart/CartEmpty.js
  src/pages/cart/CartItem.js
  src/pages/cart/CartNotEmpty.js
Labels: 멘토 리뷰 요청

#27 [33기 김완영] throttle 추가
  src/pages/OrderCheck/OrderCheck.scss
  src/pages/main/Main.js
Labels: 멘토 리뷰 요청

#26 [33기 박슬기] Add : store modal 디자인 및 기능 1차 완료
  src/Router.js
  src/components/Nav/Nav.scss
  src/components/storeModal/StoreModal.js
  src/components/storeModal/StoreModal.scss
  src/pages/productDetail/ProductDetail.scss
Labels: 멘토 리뷰 요청
